name = "hn-oauth-client-provider"
compatibility_date = "2025-06-27"
route.custom_domain = true
route.pattern = "hn.simplerauth.com"
main = "landing.ts"
assets.directory = "./public"
assets.binding = "ASSETS"
dev.port = 3001

[[durable_objects.bindings]]
name = "CODES"
class_name = "CodeDO"

[[migrations]]
new_sqlite_classes = ["CodeDO"]
tag = "v1"